export const BLACK_CARDS = [
  "Lo peor que puede pasar en una primera cita es ___.",
  "Mi terapeuta me dijo que deje de pensar tanto en ___.",
  "¿Qué encontraron dentro de la valija del presidente?",
  "El nuevo menú del McDonalds incluye ___ con papas.",
  "Según un estudio, el 80% de los argentinos prefiere ___ antes que trabajar.",
  "Mi abuela murió feliz. Sus últimas palabras fueron: ___.",
  "En el cielo te dan dos cosas: alas y ___.",
  "La nueva serie de Netflix es sobre ___ y tiene 9.8 en IMDB.",
  "Lo que más extraño de mi ex es ___.",
  "¿Por qué están todos mirando el techo en el ascensor? Por ___.",
  "El médico me dijo que si sigo así, voy a terminar con ___.",
  "Según la Biblia, los pecadores van al infierno a hacer ___.",
  "El nuevo deporte olímpico es ___ profesional.",
  "Mi jefe me llamó a la oficina para hablarme de ___.",
  "Lo que nadie te cuenta del matrimonio es ___.",
  "La inteligencia artificial reemplazará a los humanos en ___.",
  "Mi dieta nueva consiste en comer solo ___ los lunes.",
  "¿Cuál es el secreto de la felicidad? ___.",
  "El nuevo gobierno prometió resolver el problema de ___.",
  "En mi funeral quiero que pongan ___ en el cajón.",
  "La única forma de sobrevivir el trabajo es ___.",
  "Mi médico me recetó ___ tres veces al día.",
  "Lo que realmente pasa en las reuniones de padres es ___.",
  "El GPS me mandó directo a ___.",
  "Mi psicólogo me dijo que mi problema es ___.",
  "El secreto detrás del éxito de ___ sigue siendo un misterio.",
  "Según Google Maps, la ruta más corta pasa por ___.",
  "El nuevo hit del verano habla de ___ y tiene 400 millones de reproducciones.",
  "Lo único que me faltaba era ___.",
  "Cuando sea grande quiero ser ___.",
]

export const WHITE_CARDS = [
  "Llorar en el baño",
  "El ex de tu amiga",
  "Tres cervezas y un asado",
  "El WiFi del vecino",
  "Una cuota del crédito hipotecario",
  "El perro del departamento de al lado",
  "Tus propias decisiones a las 3am",
  "El delivery que nunca llega",
  "Una foto de perfil del 2015",
  "La factura de luz",
  "Tu horóscopo del lunes",
  "Un político honesto",
  "La dieta de enero",
  "Tus ahorros en dólares",
  "El médico de guardia",
  "Un emoji de berenjena",
  "La canción de tu ex",
  "Comer parado frente a la heladera",
  "El grupito de WhatsApp familiar",
  "Tus impuestos pendientes",
  "Una excusa de trabajo",
  "El botón de pánico",
  "Las vacaciones que nunca tomaste",
  "Tu alter ego alcohólico",
  "Los 40 años",
  "Una torta sin velas",
  "El vecino de arriba a las 2am",
  "Rezar sin creer en Dios",
  "El GPS que te manda mal",
  "Tu primer sueldo",
  "Hacer la vista gorda",
  "La mamá de tu mejor amigo",
  "Un certificado de defunción",
  "Robar el Wi-Fi ajeno",
  "Tus fotos de Tinder borradas",
  "El plan B que falló",
  "Contestar 'bien' cuando no estás bien",
  "La excusa del tráfico",
  "Un tatuaje en el cuello",
  "Scrollear Twitter a las 6am",
  "Fingir que entendiste el chiste",
  "Comer el sándwich de tu compañero",
  "La reunión que era un email",
  "Un like accidental a una foto vieja",
  "Tu currículum vitae",
  "El karma que no llega nunca",
  "Una selfie en el velorio",
  "La línea de atención al cliente",
  "Dios mirando para otro lado",
  "El vecino que no saluda",
  "Una dieta de 3 días",
  "El candidato que votaste",
  "Tu contraseña anotada en papel",
  "Fingir que tenés planes",
  "La cuota del gimnasio que no vas",
  "Tu jefe a las 8am",
  "Un asado sin chimichurri",
  "El celular sin batería",
  "Una discusión en Twitter",
  "Tu lado oscuro",
  "El ex que te bloqueó",
  "Una factura de AFIP",
  "Mirar Netflix solo un episodio más",
  "Mandarte un mensaje a vos mismo",
  "El grupo de trabajo del secundario",
  "Tu compañero de oficina que come fuerte",
  "Poner la alarma y no levantarte",
  "Hablar solo en el auto",
  "El médico que te dice 'esto es del estrés'",
  "Un asado con veganos",
  "Tus excusas para no ir al gym",
  "La cuenta de Spotify que compartís",
  "Tu cara en las fotos de grupo",
]

export function shuffle(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
